### PR TITLE
Update AndroidManifest.xml

### PR DESCRIPTION
**Pull request by tamilan007**
This will helful 
By this we can view root files of app in fx file manager

### CODE REVIEW

**Comment by tiann** [comment]
1. You can use SAF to access internal files
2. install root exploer in twoyi can also manage internal files

**Comment by tamilan007** [comment]
@tiann 
I entered this code to access root folders of this app in real system 
This code will work even in non rooted main system

**Comment by tamilan007** [comment]
Non root users in main system can still able to view the files in root folder of this app in 
/data/data/

**Comment by tiann** [comment]
It is not secure, you can install a file manager in twoyi.

**Pull request closed without merging**
